'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.488
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SQLClue.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Archive in Progress.
        '''</summary>
        Friend ReadOnly Property ActiveArchiveAbortCaption() As String
            Get
                Return ResourceManager.GetString("ActiveArchiveAbortCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A background Archive process owned by this window is in progress. Closing the window will cancel the archive. Select [Yes] to Close SQLClue and cancel this archive?.
        '''</summary>
        Friend ReadOnly Property ActiveArchiveAbortText() As String
            Get
                Return ResourceManager.GetString("ActiveArchiveAbortText", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ActualSizeHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActualSizeHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AddTableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddTableHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration Compare Settings.
        '''</summary>
        Friend ReadOnly Property AdvancedSettings() As String
            Get
                Return ResourceManager.GetString("AdvancedSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend ReadOnly Property All() As String
            Get
                Return ResourceManager.GetString("All", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Annotation_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Annotation_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Appending script: {0} of {1}.
        '''</summary>
        Friend ReadOnly Property AppendingScript() As String
            Get
                Return ResourceManager.GetString("AppendingScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Schedule Id {0} Cancelled.
        '''</summary>
        Friend ReadOnly Property ArchiveCancelled() As String
            Get
                Return ResourceManager.GetString("ArchiveCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Schedule Id {0} Complete.
        '''</summary>
        Friend ReadOnly Property ArchiveComplete() As String
            Get
                Return ResourceManager.GetString("ArchiveComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration from [{0}] to Include in Archive.
        '''</summary>
        Friend ReadOnly Property ArchiveConfigurationTreeTitle() As String
            Get
                Return ResourceManager.GetString("ArchiveConfigurationTreeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Schedule Id {0} Exception.
        '''</summary>
        Friend ReadOnly Property ArchiveException() As String
            Get
                Return ResourceManager.GetString("ArchiveException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue: SQL Configuration Archive Failed.
        '''</summary>
        Friend ReadOnly Property ArchiveFailNotificationName() As String
            Get
                Return ResourceManager.GetString("ArchiveFailNotificationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are unsaved archive configuration changes. Select [Yes] to save changes now, [No] to abandon all changes or [Cancel] to close this dialog.
        '''</summary>
        Friend ReadOnly Property ArchiveHasUnsavedChanges() As String
            Get
                Return ResourceManager.GetString("ArchiveHasUnsavedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a Frequency between 1 and {0} {1}s .
        '''</summary>
        Friend ReadOnly Property ArchiveInterval() As String
            Get
                Return ResourceManager.GetString("ArchiveInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalPlural() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set Interval Type then Frequency .
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalSelect() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Interval Type Seleceted!.
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalSelectFailed() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalSelectFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Frequency Validation Failed.
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalSelectFailedCaption() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalSelectFailedCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive every {0} {1}{2}.
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalSentence() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalSentence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select [Interval Type] before selecting [Interval].
        '''</summary>
        Friend ReadOnly Property ArchiveIntervalSequence() As String
            Get
                Return ResourceManager.GetString("ArchiveIntervalSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; Alert not found..
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationAlertNotFound() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationAlertNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This notification must be maintained using SQL Server tools..
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationHasBeenCustomized() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationHasBeenCustomized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operator {0} will not receive {1} notificatons because no Notification Methods have been set..
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationNoMethodsEnabled() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationNoMethodsEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert Notifications not supported on SQL Server Expresss.
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationNoSQLExpress() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationNoSQLExpress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A SQL Agent Operator must be properly configured before Alert Notifications can be enabled and sent..
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationOperatorRequired() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationOperatorRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select one or more - If none available for selection the SQL Agent Operator is not correctly configured..
        '''</summary>
        Friend ReadOnly Property ArchiveNotificationSelectMethods() As String
            Get
                Return ResourceManager.GetString("ArchiveNotificationSelectMethods", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure and Schedule DDL and Configuration Archive Automation .
        '''</summary>
        Friend ReadOnly Property ArchivePlanningOverview() As String
            Get
                Return ResourceManager.GetString("ArchivePlanningOverview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to a SQL Instance, then manage the schedules and configuration for that instance..
        '''</summary>
        Friend ReadOnly Property ArchivePlanningRequestInvalid() As String
            Get
                Return ResourceManager.GetString("ArchivePlanningRequestInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduling next run date.
        '''</summary>
        Friend ReadOnly Property ArchiveRescheduled() As String
            Get
                Return ResourceManager.GetString("ArchiveRescheduled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration Archive Schedules for SQL Instance [{0}].
        '''</summary>
        Friend ReadOnly Property ArchiveScheduleViewTitle() As String
            Get
                Return ResourceManager.GetString("ArchiveScheduleViewTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Schedule Id {0} Starting.
        '''</summary>
        Friend ReadOnly Property ArchiveStarting() As String
            Get
                Return ResourceManager.GetString("ArchiveStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue: SQL Configuration Archive Succeeded.
        '''</summary>
        Friend ReadOnly Property ArchiveSuccessNotificationName() As String
            Get
                Return ResourceManager.GetString("ArchiveSuccessNotificationName", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property AttachmentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AttachmentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_reportHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_reportHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_StackOfReportsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_StackOfReportsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a Boolean.
        '''</summary>
        Friend ReadOnly Property BooleanAdvOptions() As String
            Get
                Return ResourceManager.GetString("BooleanAdvOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to bool.
        '''</summary>
        Friend ReadOnly Property BooleanAdvOptionsAbbr() As String
            Get
                Return ResourceManager.GetString("BooleanAdvOptionsAbbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toggles between true and false for this setting..
        '''</summary>
        Friend ReadOnly Property BooleanAdvOptionsHelp() As String
            Get
                Return ResourceManager.GetString("BooleanAdvOptionsHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelled.
        '''</summary>
        Friend ReadOnly Property Cancelled() As String
            Get
                Return ResourceManager.GetString("Cancelled", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Collection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CommentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compare Cancelled.
        '''</summary>
        Friend ReadOnly Property CompareCancelled() As String
            Get
                Return ResourceManager.GetString("CompareCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Compare Complete.
        '''</summary>
        Friend ReadOnly Property CompareComplete() As String
            Get
                Return ResourceManager.GetString("CompareComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; 
        '''          &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;&lt;title&gt;SQLClue Compare&lt;/title&gt;&lt;/head&gt;
        '''&lt;frameset cols=&quot;100%&quot; rows=&quot;10%,80%,10%&quot; frameborder=&quot;1&quot;&gt;
        '''&lt;frame src=&quot;SQLClueTitle.htm&quot; scrolling=&quot;no&quot; name=&quot;top&quot;&gt;
        '''&lt;frameset cols=&quot;50%,50%&quot; rows=&quot;100%&quot; frameborder=&quot;1&quot;&gt;
        '''&lt;frame src=&quot;SQLClueResultsA.htm&quot; scrolling=&quot;yes&quot; name=&quot;left&quot;&gt;
        '''&lt;frame src=&quot;SQLClueResultsB.htm&quot; scrolling=&quot;yes&quot; name=&quot;right&quot;&gt;
        '''&lt;/frameset&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CompareHTML() As String
            Get
                Return ResourceManager.GetString("CompareHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/td&gt;&lt;/tr&gt;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLEndLine() As String
            Get
                Return ResourceManager.GetString("CompareHTMLEndLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueCompare.htm.
        '''</summary>
        Friend ReadOnly Property CompareHTMLFileName() As String
            Get
                Return ResourceManager.GetString("CompareHTMLFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; 
        '''          &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;&lt;title&gt;SQLClue Compare Key&lt;/title&gt;&lt;/head&gt;
        '''&lt;body style=&quot;font-family: Lucida Console; font-size: 10px&quot;&gt;
        '''&lt;table width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td style=&quot;text-align: center&quot;&gt;
        '''&lt;table border=&quot;1&quot; width=&quot;40%&quot; align=&quot;center&quot;&gt;&lt;tr&gt;&lt;td&gt;Results Key&lt;/td&gt;
        '''&lt;td style=&quot;background-color: #{0}; color: #{1}&quot;&gt;matched&lt;/td&gt;
        '''&lt;td style=&quot;background-color: #{2}; color: #{3}&quot;&gt;differen [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLKey() As String
            Get
                Return ResourceManager.GetString("CompareHTMLKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueKey.htm.
        '''</summary>
        Friend ReadOnly Property CompareHTMLKeyFileName() As String
            Get
                Return ResourceManager.GetString("CompareHTMLKeyFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; 
        '''          &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;&lt;title&gt;SQLClue Compare Panel 1&lt;/title&gt; &lt;/head&gt;
        '''&lt;body style=&quot;font-family: Lucida Console; font-size: 10px&quot;&gt;
        '''&lt;table width=&quot;500%&quot;&gt;
        '''{0}
        '''&lt;/table&gt;&lt;/body&gt;&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLResultsA() As String
            Get
                Return ResourceManager.GetString("CompareHTMLResultsA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueResultsA.htm.
        '''</summary>
        Friend ReadOnly Property CompareHTMLResultsAFileName() As String
            Get
                Return ResourceManager.GetString("CompareHTMLResultsAFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot;&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; 
        '''      content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''&lt;title&gt;SQLClue Compare Panel 2&lt;/title&gt;
        '''&lt;script type=&quot;text/javascript&quot;&gt;
        '''{0}
        '''&lt;/script&gt;
        '''&lt;/head&gt;
        '''&lt;body style=&quot;font-family: Lucida Console; font-size: 10px&quot;&gt;
        '''&lt;table width=&quot;500%&quot;&gt;
        '''{1}
        '''&lt;/table&gt;&lt;/body&gt;&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLResultsB() As String
            Get
                Return ResourceManager.GetString("CompareHTMLResultsB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueResultsB.htm.
        '''</summary>
        Friend ReadOnly Property CompareHTMLResultsBFileName() As String
            Get
                Return ResourceManager.GetString("CompareHTMLResultsBFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var _run;
        '''if(navigator.userAgent.indexOf(&quot;Firefox&quot;)!=-1||navigator.appName==&quot;Microsoft Internet Explorer&quot;)
        '''{_run=false;} 
        '''else 
        '''{_run= true;}
        '''function scrollR()
        '''{var left = (window.pageXOffset)?(window.pageXOffset):(document.documentElement)?document.documentElement.scrollLeft:document.body.scrollLeft;
        '''var top = (window.pageYOffset)?(window.pageYOffset):(document.documentElement)?document.documentElement.scrollTop:document.body.scrollTop;
        '''parent.frames[&quot;left&quot;].scrollTo(left,top);}
        '''function searchSc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLScrollerJavaScript() As String
            Get
                Return ResourceManager.GetString("CompareHTMLScrollerJavaScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;background-color: #{0}; color: #{1}&quot;&gt;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLStartLine() As String
            Get
                Return ResourceManager.GetString("CompareHTMLStartLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; 
        '''          &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;SQLClue Compare Heading&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body style=&quot;font-family: Lucida Console; font-size: 10px&quot;&gt;
        '''&lt;table width=&quot;100%&quot;&gt;
        '''&lt;tr&gt;
        '''&lt;td style=&quot;font-weight: bold; text-align: left&quot;&gt;
        '''{0}
        '''&lt;/td&gt;
        '''&lt;td style=&quot;font-weight: bold; text-align: right&quot;&gt;
        '''{1}
        '''&lt;/td&gt;
        '''&lt;/tr&gt;
        '''&lt;/table&gt;
        '''&lt;/body&gt;&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property CompareHTMLTitle() As String
            Get
                Return ResourceManager.GetString("CompareHTMLTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueTitle.htm.
        '''</summary>
        Friend ReadOnly Property CompareHTMLTitleFileName() As String
            Get
                Return ResourceManager.GetString("CompareHTMLTitleFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance.
        '''</summary>
        Friend ReadOnly Property CompareInstanceLabel() As String
            Get
                Return ResourceManager.GetString("CompareInstanceLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compare SQL Server Configuration and Scripted Objects.
        '''</summary>
        Friend ReadOnly Property CompareOverview() As String
            Get
                Return ResourceManager.GetString("CompareOverview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- Node: [{0}|{1}].
        '''</summary>
        Friend ReadOnly Property CompareResultNodeItemLabel() As String
            Get
                Return ResourceManager.GetString("CompareResultNodeItemLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- Node: [{0}].
        '''</summary>
        Friend ReadOnly Property CompareResultNodeLabel() As String
            Get
                Return ResourceManager.GetString("CompareResultNodeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- Origin: [{0}].
        '''</summary>
        Friend ReadOnly Property CompareResultOriginLabel() As String
            Get
                Return ResourceManager.GetString("CompareResultOriginLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- Version: [{0}].
        '''</summary>
        Friend ReadOnly Property CompareResultVersionLabel() As String
            Get
                Return ResourceManager.GetString("CompareResultVersionLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rich Text Files (*.rtf)|*.rtf|SQL Files (*.sql)|*.sql|Text Files (*.txt)|*.txt.
        '''</summary>
        Friend ReadOnly Property CompareSaveTextFilter() As String
            Get
                Return ResourceManager.GetString("CompareSaveTextFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comparing....
        '''</summary>
        Friend ReadOnly Property CompareStarting() As String
            Get
                Return ResourceManager.GetString("CompareStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration Compare.
        '''</summary>
        Friend ReadOnly Property CompareText() As String
            Get
                Return ResourceManager.GetString("CompareText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compare Validation Failed..
        '''</summary>
        Friend ReadOnly Property CompareValidationFailureCaption() As String
            Get
                Return ResourceManager.GetString("CompareValidationFailureCaption", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property compareversionsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compareversionsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comparing [{0}] and  [{1}] .
        '''</summary>
        Friend ReadOnly Property Comparing() As String
            Get
                Return ResourceManager.GetString("Comparing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CompIn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompIn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CompIn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompIn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CompOut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompOut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CompOut1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompOut1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} now connected to [{0}].
        '''</summary>
        Friend ReadOnly Property ConnectedToSQL() As String
            Get
                Return ResourceManager.GetString("ConnectedToSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecting to [{0}]....
        '''</summary>
        Friend ReadOnly Property ConnectingToSQL() As String
            Get
                Return ResourceManager.GetString("ConnectingToSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} failed to Connect to [{1}].
        '''</summary>
        Friend ReadOnly Property ConnectionToSQLFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionToSQLFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to SQLClue Repository.
        '''</summary>
        Friend ReadOnly Property ConnectToAnyRepository() As String
            Get
                Return ResourceManager.GetString("ConnectToAnyRepository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect to Target SQL Instance.
        '''</summary>
        Friend ReadOnly Property ConnectToAnySQL() As String
            Get
                Return ResourceManager.GetString("ConnectToAnySQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Bill Wunder at bwunder@yahoo.com for all support and licensing inquiries.  .
        '''</summary>
        Friend ReadOnly Property ContactBillAt() As String
            Get
                Return ResourceManager.GetString("ContactBillAt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CopyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_MoveFirstHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveFirstHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_MoveLastHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_MoveNextHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_MovePreviousHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_NewRecordHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT ISNULL(ApplicationName, &apos;&lt;none&gt;&apos;) AS ApplicationName
        '''     , Count(*) As [rows]
        '''     , RANK() OVER(ORDER BY Count(*) DESC) AS [rank]
        '''FROM sys.traces t
        '''CROSS APPLY sys.fn_trace_gettable( LEFT( t.[path], LEN(t.[path]) - PATINDEX( &apos;%\%&apos;, REVERSE(t.[path]) ) ) + &apos;\log.trc&apos;, DEFAULT ) As trc 
        '''WHERE t.is_default = 1
        '''AND trc.StartTime BETWEEN &apos;{0}&apos; AND &apos;{1}&apos;
        '''GROUP BY ISNULL(ApplicationName, &apos;&lt;none&gt;&apos;)
        '''ORDER BY ApplicationName.
        '''</summary>
        Friend ReadOnly Property DefaultTraceApplicationsQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceApplicationsQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT cat.name, COUNT(*) as rows
        '''    , RANK() OVER(ORDER BY Count(*) DESC) AS [rank]
        '''FROM sys.traces t
        '''CROSS APPLY sys.fn_trace_gettable( LEFT( t.[path], LEN(t.[path]) - PATINDEX( &apos;%\%&apos;, REVERSE(t.[path]) ) ) + &apos;\log.trc&apos;, DEFAULT ) As trc 
        '''JOIN sys.trace_events evt
        '''ON trc.EventClass = evt.trace_event_id
        '''JOIN sys.trace_categories cat
        '''ON evt.category_id = cat.category_id
        '''WHERE t.is_default = 1
        '''AND trc.StartTime BETWEEN  &apos;{0}&apos; AND &apos;{1}&apos;
        '''GROUP BY cat.name
        '''ORDER BY cat.name;.
        '''</summary>
        Friend ReadOnly Property DefaultTraceCategoriesQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceCategoriesQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT COALESCE( trc.DatabaseName
        '''               , DB_NAME(trc.DatabaseID)
        '''               ,&apos;&lt;none&gt;&apos;) AS DatabaseName
        '''               , Count(*) As [rows]
        '''               , RANK() OVER(ORDER BY Count(*) DESC) AS [rank]
        '''FROM sys.traces t
        '''CROSS APPLY sys.fn_trace_gettable( LEFT( t.[path]
        '''                                       , LEN(t.[path]) 
        '''                                       - PATINDEX( &apos;%\%&apos;
        '''                                                 , REVERSE(t.[path]) ) ) 
        '''                                [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DefaultTraceDatabasesQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceDatabasesQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT cat.name AS [EventCategory]
        '''     , evt.name AS [EventClass]
        '''		 , ISNULL( sub.subclass_name, &apos;&lt;none&gt;&apos;) AS [EventSubClass]
        '''		 , COALESCE( trc.DatabaseName, DB_NAME(trc.DatabaseID), &apos;&lt;none&gt;&apos; ) as [Database]
        '''		 , COALESCE( SUSER_SNAME(trc.LoginSid), trc.NtUserName, &apos;&lt;none&gt;&apos; ) AS [Login]
        '''     , ISNULL( trc.ApplicationName, &apos;&lt;none&gt;&apos;) As Application
        '''     , trc.StartTime
        '''     , ISNULL( trc.HostName, &apos;&lt;none&gt;&apos;) AS Host
        '''     , ISNULL( type.ObjectType, &apos;&apos; ) AS ObjType
        '''		 , ISNULL( &apos; || Severity: &apos; + CAS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DefaultTraceEventsQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceEventsQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT ISNULL(trc.HostName, &apos;&lt;none&gt;&apos;) AS HostName
        '''     , Count(*) As [rows]
        '''     , RANK() OVER(ORDER BY Count(*)) AS [rank]
        '''FROM sys.traces t
        '''CROSS APPLY sys.fn_trace_gettable( LEFT( t.[path], LEN(t.[path]) - PATINDEX( &apos;%\%&apos;, REVERSE(t.[path]) ) ) + &apos;\log.trc&apos;, DEFAULT ) As trc 
        '''WHERE t.is_default = 1
        '''AND trc.StartTime BETWEEN &apos;{0}&apos; AND &apos;{1}&apos;
        '''GROUP BY ISNULL(trc.HostName, &apos;&lt;none&gt;&apos;)
        '''ORDER BY HostName.
        '''</summary>
        Friend ReadOnly Property DefaultTraceHostsQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceHostsQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT ISNULL(LoginName, &apos;&lt;none&gt;&apos;) AS LoginName
        '''     , Count(*) As [rows]
        '''     , RANK() OVER(ORDER BY Count(*) DESC) AS [rank]
        '''FROM sys.traces t
        '''CROSS APPLY sys.fn_trace_gettable( LEFT( t.[path], LEN(t.[path]) - PATINDEX( &apos;%\%&apos;, REVERSE(t.[path]) ) ) + &apos;\log.trc&apos;, DEFAULT ) As trc 
        '''WHERE t.is_default = 1
        '''AND trc.StartTime BETWEEN &apos;{0}&apos; AND &apos;{1}&apos;
        '''GROUP BY ISNULL(LoginName,&apos;&lt;none&gt;&apos;)
        '''ORDER BY LoginName.
        '''</summary>
        Friend ReadOnly Property DefaultTraceLoginsQuery() As String
            Get
                Return ResourceManager.GetString("DefaultTraceLoginsQuery", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Target Instance.
        '''</summary>
        Friend ReadOnly Property DeleteConfigCaption() As String
            Get
                Return ResourceManager.GetString("DeleteConfigCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove all archive configuration for [{0}]?.
        '''</summary>
        Friend ReadOnly Property DeleteConfigText() As String
            Get
                Return ResourceManager.GetString("DeleteConfigText", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property DeleteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Differences Found.
        '''</summary>
        Friend ReadOnly Property Different() As String
            Get
                Return ResourceManager.GetString("Different", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes have been made but not saved.
        '''</summary>
        Friend ReadOnly Property Dirty() As String
            Get
                Return ResourceManager.GetString("Dirty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to disabled.
        '''</summary>
        Friend ReadOnly Property Disabled() As String
            Get
                Return ResourceManager.GetString("Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Disconnecting from SQL Instance [{1}].
        '''</summary>
        Friend ReadOnly Property DisconnectingFromSQL() As String
            Get
                Return ResourceManager.GetString("DisconnectingFromSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue Automation Controller start-up account access must be granted to enable automated synchronization between a document and the SQLClue Runbook. Verify the access requirement listed or forward this information to the security authority or SQLClue Administrator [{0}] before commiting this Runbook Topic action..
        '''</summary>
        Friend ReadOnly Property DocumentSecurityMessage() As String
            Get
                Return ResourceManager.GetString("DocumentSecurityMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done.
        '''</summary>
        Friend ReadOnly Property Done() As String
            Get
                Return ResourceManager.GetString("Done", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_RedoHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_RedoHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_UndoHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_UndoHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EditInformationHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditInformationHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to enabled.
        '''</summary>
        Friend ReadOnly Property Enabled() As String
            Get
                Return ResourceManager.GetString("Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errors Occurred.
        '''</summary>
        Friend ReadOnly Property ErrorsOccurred() As String
            Get
                Return ResourceManager.GetString("ErrorsOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabling SQLClue Event Notifications on SQL Instance [{0}].
        '''</summary>
        Friend ReadOnly Property EventNotificationsDisable() As String
            Get
                Return ResourceManager.GetString("EventNotificationsDisable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabling SQLClue Event Notifications on SQL Instance [{0}].
        '''</summary>
        Friend ReadOnly Property EventNotificationsEnable() As String
            Get
                Return ResourceManager.GetString("EventNotificationsEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDL Event Notifications not supported for SQL Server Version [{1}] ([{0}]).
        '''</summary>
        Friend ReadOnly Property EventNotificationsNotSupported() As String
            Get
                Return ResourceManager.GetString("EventNotificationsNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event Notifications {0} on SQL Instance [{1}].
        '''</summary>
        Friend ReadOnly Property EventNotificationStateChanging() As String
            Get
                Return ResourceManager.GetString("EventNotificationStateChanging", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Instance [{0}] is not available. SQLClue Event Notification configuration cannot be removed from the target instance at this time. To prevent an out of space condition in the future have a DBA execute the &apos;uninstSQLClueDDLEventNotifications.sql&apos; script from the SQLClue Resources Library in database [{1}] on target [{0}] when the SQL Server is available. .
        '''</summary>
        Friend ReadOnly Property EvtNotifyDropFailed() As String
            Get
                Return ResourceManager.GetString("EvtNotifyDropFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For more information or support for this error see http://www.bwunder.com or email Bill at bwunder@yahoo.com..
        '''</summary>
        Friend ReadOnly Property ExceptionInfoMsg() As String
            Get
                Return ResourceManager.GetString("ExceptionInfoMsg", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ExpirationHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExpirationHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Favorites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favorites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flag_redHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag_redHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FormRunHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormRunHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property HelpOverview() As String
            Get
                Return ResourceManager.GetString("HelpOverview", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property holmes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holmes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A collection of type [{0}] cannot be compared with a collection of type [{1}].
        '''</summary>
        Friend ReadOnly Property InvalidCollectionCompare() As String
            Get
                Return ResourceManager.GetString("InvalidCollectionCompare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A collection of {0} and the item {1} cannot be compared. Select either a collection from each source or an item from each source..
        '''</summary>
        Friend ReadOnly Property InvalidCompare() As String
            Get
                Return ResourceManager.GetString("InvalidCompare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Option [ECMA Script] can be used only with options [Ignore Case], [Multi-line] and [Ignore Pattern Whitespace]. Combining with any other options is not supported..
        '''</summary>
        Friend ReadOnly Property InvalidECMAScriptSelection() As String
            Get
                Return ResourceManager.GetString("InvalidECMAScriptSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An item of type [{0}] cannot be compared with an item of type [{1}].
        '''</summary>
        Friend ReadOnly Property InvalidItemCompare() As String
            Get
                Return ResourceManager.GetString("InvalidItemCompare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For maximum security, password editing is not permitted.  Re-enter the complete password..
        '''</summary>
        Friend ReadOnly Property InvalidPasswordEdit() As String
            Get
                Return ResourceManager.GetString("InvalidPasswordEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Repository {1} is invalid or contains no archives.
        '''</summary>
        Friend ReadOnly Property InvalidRepository() As String
            Get
                Return ResourceManager.GetString("InvalidRepository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Passwords allow alpha-numeric, symbol and punctuaion charaters only..
        '''</summary>
        Friend ReadOnly Property InvalidSQLPasswordChar() As String
            Get
                Return ResourceManager.GetString("InvalidSQLPasswordChar", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright (c) 2007 - 2012 Bill Wunder
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights
        '''to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        '''copies of the Software, and to permit persons to whom the Software is
        '''furnished to do so, subject to the following conditions:
        '''
        '''The above copyright notice and [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property License() As String
            Get
                Return ResourceManager.GetString("License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fetching hierarchy for the most recent archive of SQL Instance [{0}].
        '''</summary>
        Friend ReadOnly Property LoadingRepositoryHierarchyForInstance() As String
            Get
                Return ResourceManager.GetString("LoadingRepositoryHierarchyForInstance", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property LoadOutput() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadOutput", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Managed Computer [{0}].
        '''</summary>
        Friend ReadOnly Property ManagedComputerNodeName() As String
            Get
                Return ResourceManager.GetString("ManagedComputerNodeName", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MessageQueuing() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MessageQueuing", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Messages() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Messages", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select one Database from each SQL Instance. Database A - [{0}]; Database B - [{1}].
        '''</summary>
        Friend ReadOnly Property NoDatabaseSelected() As String
            Get
                Return ResourceManager.GetString("NoDatabaseSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *.
        '''</summary>
        Friend ReadOnly Property NodePlaceHolder() As String
            Get
                Return ResourceManager.GetString("NodePlaceHolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ready to compare {1}.
        '''</summary>
        Friend ReadOnly Property NodeSelected() As String
            Get
                Return ResourceManager.GetString("NodeSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No [{0}] found in at least one source using the currently configured settings. .
        '''</summary>
        Friend ReadOnly Property NoItemInDB() As String
            Get
                Return ResourceManager.GetString("NoItemInDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to item or script line not found in other source.
        '''</summary>
        Friend ReadOnly Property NoMatch() As String
            Get
                Return ResourceManager.GetString("NoMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The value entered must be numeric.
        '''</summary>
        Friend ReadOnly Property NonNumericEntry() As String
            Get
                Return ResourceManager.GetString("NonNumericEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Servers found in local Repository.
        '''</summary>
        Friend ReadOnly Property NoRepositoryServerNodes() As String
            Get
                Return ResourceManager.GetString("NoRepositoryServerNodes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{0}] must be selected. {0}A = [{1}]; {0}B = [{2}] .
        '''</summary>
        Friend ReadOnly Property NoSelection() As String
            Get
                Return ResourceManager.GetString("NoSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The smo EnumAvailableSqlServers was not able to detect any SQL Servers.
        '''</summary>
        Friend ReadOnly Property NoSqlServers() As String
            Get
                Return ResourceManager.GetString("NoSqlServers", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property NoteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to an Integer (numeric).
        '''</summary>
        Friend ReadOnly Property NumericAdvOptions() As String
            Get
                Return ResourceManager.GetString("NumericAdvOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to int.
        '''</summary>
        Friend ReadOnly Property NumericAdvOptionsAbbr() As String
            Get
                Return ResourceManager.GetString("NumericAdvOptionsAbbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adjusts the numeric value for [{0}]..
        '''</summary>
        Friend ReadOnly Property NumericAdvOptionsHelp() As String
            Get
                Return ResourceManager.GetString("NumericAdvOptionsHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SQL Configuration Repository must be installed before SQLClue can be licensed.  Use the SQL Configuration Repository option of the Tools Menu to install the component. It is also recommended that an archive of the host SQL Instance be completed before licensing to verify the installation. .
        '''</summary>
        Friend ReadOnly Property OnlyLicenceIfDBInstalled() As String
            Get
                Return ResourceManager.GetString("OnlyLicenceIfDBInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origin.
        '''</summary>
        Friend ReadOnly Property Origin() As String
            Get
                Return ResourceManager.GetString("Origin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TargetSQLInstance.
        '''</summary>
        Friend ReadOnly Property OriginArchiveTarget() As String
            Get
                Return ResourceManager.GetString("OriginArchiveTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder.
        '''</summary>
        Friend ReadOnly Property OriginFile() As String
            Get
                Return ResourceManager.GetString("OriginFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repository.
        '''</summary>
        Friend ReadOnly Property OriginRepository() As String
            Get
                Return ResourceManager.GetString("OriginRepository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLInstance.
        '''</summary>
        Friend ReadOnly Property OriginSQLInstance() As String
            Get
                Return ResourceManager.GetString("OriginSQLInstance", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PlayHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PointerHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PointerHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Friend ReadOnly Property Ready() As String
            Get
                Return ResourceManager.GetString("Ready", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshBW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshBW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RelationshipsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RelationshipsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;reload list...&gt;.
        '''</summary>
        Friend ReadOnly Property ReloadList() As String
            Get
                Return ResourceManager.GetString("ReloadList", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property RepeatHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RepeatHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue Management &amp; Analysis Views.
        '''</summary>
        Friend ReadOnly Property ReportViewerOverview() As String
            Get
                Return ResourceManager.GetString("ReportViewerOverview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RepositoryCollection.
        '''</summary>
        Friend ReadOnly Property RepositoryCollection() As String
            Get
                Return ResourceManager.GetString("RepositoryCollection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Configuration Repository appears to be corrupted or has been previously uninstalled. The setup dialog will be populated with cached values for the existing Configuration Repository. Use these values to reconnect to the existing data store or provide connection information to another database/server if preferred..
        '''</summary>
        Friend ReadOnly Property RepositoryCorrupt() As String
            Get
                Return ResourceManager.GetString("RepositoryCorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create SQLClue DDL &amp; Configuration Repository?.
        '''</summary>
        Friend ReadOnly Property RepositoryInstallCaption() As String
            Get
                Return ResourceManager.GetString("RepositoryInstallCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It is recommended that the SQL Server DDL and Configuration Repository database is installed when SQLClue is installed. It is to the advantage of most users to respond [Yes]. Unless only the SQLClue Compare component is desired – an unlikely first use yet entirely appropriate supplemental configuration, the creation of this database is required by SQLClue.  For script details see file [{0}] at {1})
        '''
        '''HOST SQL SERVER REQUIREMENTS 
        '''A user specified local SQL Server 2005 instance will host the Repository. Th [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RepositoryInstallPromtpt() As String
            Get
                Return ResourceManager.GetString("RepositoryInstallPromtpt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RepositoryItem.
        '''</summary>
        Friend ReadOnly Property RepositoryItem() As String
            Get
                Return ResourceManager.GetString("RepositoryItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SQL Configuration Repository is not enabled .
        '''</summary>
        Friend ReadOnly Property RepositoryNotEnabled() As String
            Get
                Return ResourceManager.GetString("RepositoryNotEnabled", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rpsh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rpsh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes for Topic: {0}.
        '''</summary>
        Friend ReadOnly Property RunbookNotesHeader() As String
            Get
                Return ResourceManager.GetString("RunbookNotesHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administration of Online Knowledge and Information Sharing Runbook .
        '''</summary>
        Friend ReadOnly Property RunbookOverview() As String
            Get
                Return ResourceManager.GetString("RunbookOverview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Topics for {0} {1}.
        '''</summary>
        Friend ReadOnly Property RunbookTopicListHeader() As String
            Get
                Return ResourceManager.GetString("RunbookTopicListHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Differences Found.
        '''</summary>
        Friend ReadOnly Property Same() As String
            Get
                Return ResourceManager.GetString("Same", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAllHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAllHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SBQueue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SBQueue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SBQueueOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SBQueueOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notice: Security best practices dictate that for all but the very least sensitive of applications the SQLClue repository is never directly exposed to the Internet..
        '''</summary>
        Friend ReadOnly Property SecurityMessage() As String
            Get
                Return ResourceManager.GetString("SecurityMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Select a File.
        '''</summary>
        Friend ReadOnly Property SelectAFile() As String
            Get
                Return ResourceManager.GetString("SelectAFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Select a node.
        '''</summary>
        Friend ReadOnly Property SelectANode() As String
            Get
                Return ResourceManager.GetString("SelectANode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the folder containing  the SQL Server configuration documentation text or script files to be used in this compare..
        '''</summary>
        Friend ReadOnly Property SelectFileFolder() As String
            Get
                Return ResourceManager.GetString("SelectFileFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Select Origin.
        '''</summary>
        Friend ReadOnly Property SelectOrigin() As String
            Get
                Return ResourceManager.GetString("SelectOrigin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Select a SQL Instance.
        '''</summary>
        Friend ReadOnly Property SelectServer() As String
            Get
                Return ResourceManager.GetString("SelectServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Automation Controller Service could not be started at this time. The Automation Controller must be running before any scheduled SQLClue activities will be completed. .
        '''</summary>
        Friend ReadOnly Property ServiceDidNotStartMessage() As String
            Get
                Return ResourceManager.GetString("ServiceDidNotStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue Automation Controller service is enabled in the SQLClue application but not found on host {0}. SQLClue application settings are now updated to resolve conflict..
        '''</summary>
        Friend ReadOnly Property ServiceEnabledButNotInstalled() As String
            Get
                Return ResourceManager.GetString("ServiceEnabledButNotInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue Automation Controller service installed on host {0} but not enabled in the SQLClue application. SQLClue application settings are now updated to resolve conflict..
        '''</summary>
        Friend ReadOnly Property ServiceInstalledButNotEnabled() As String
            Get
                Return ResourceManager.GetString("ServiceInstalledButNotEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to remove the SQL Server login from Instance [{0}] for the SQLClue Automation Controller service account [{1}]. Remove the login when the SQL Server is available..
        '''</summary>
        Friend ReadOnly Property ServiceLoginDropFailed() As String
            Get
                Return ResourceManager.GetString("ServiceLoginDropFailed", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property servicepaused() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("servicepaused", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property servicerunning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("servicerunning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must be a local administrator on host
        '''   {0}
        '''to install the Automation Controller service.
        '''
        '''The installer requires you to enter a Windows 
        '''user name and password for use as the Windows 
        '''service start-up account
        '''
        '''The Service start-up account will be added to 
        '''the [sysadmin] Fixed Server Role on targeted 
        '''SQL Server instances that use where SQLClue
        '''is configured to connect using Windows 
        '''authentication.
        '''
        '''Monitor the Application Event Log on the host
        '''for all event messages from source &apos;{1}&apos;. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ServiceSetupMessage() As String
            Get
                Return ResourceManager.GetString("ServiceSetupMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting SQLClue Service... .
        '''</summary>
        Friend ReadOnly Property ServiceStartupMessage() As String
            Get
                Return ResourceManager.GetString("ServiceStartupMessage", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property servicestopped() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("servicestopped", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property serviceunknown() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("serviceunknown", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: No Local SQL Server Detected.
        '''</summary>
        Friend ReadOnly Property SetupNoServersCaption() As String
            Get
                Return ResourceManager.GetString("SetupNoServersCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClue has not been able to detect any local SQL Server instances. This may be because the SQL Browser Service is not running. It may also be an indication that SQL Server is not installed on the local system. [{0}] requires a pre-existing local SQL Server. Select [OK] to continue and enter the name of an existing local SQL Instance. Select [Cancel] to exit and quit this request to run [{0}]..
        '''</summary>
        Friend ReadOnly Property SetupNoServersMessage() As String
            Get
                Return ResourceManager.GetString("SetupNoServersMessage", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SingleMessage() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SingleMessage", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SpinningTwoHeadedDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpinningTwoHeadedDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enumerating Servers... If this operation is taking too long or not providing a complete list of servers, try changing the [Server Enum Scope] in the Compare form [Advanced Settings].
        '''</summary>
        Friend ReadOnly Property SplashMsg() As String
            Get
                Return ResourceManager.GetString("SplashMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeAdd() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeChange() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeDelete() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeDelete", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sqlclue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlclue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SQLClue96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLClue96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLClueSvc.
        '''</summary>
        Friend ReadOnly Property SQLClueService() As String
            Get
                Return ResourceManager.GetString("SQLClueService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property SQLInstance() As String
            Get
                Return ResourceManager.GetString("SQLInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using SQL Server Authentication is not recommended. The ability to use SQL Server authentication is provided for situations where a trusted connection is not possible. .
        '''</summary>
        Friend ReadOnly Property SQLLoginForCompareNotRecommended() As String
            Get
                Return ResourceManager.GetString("SQLLoginForCompareNotRecommended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning - Password Exposure Risk.
        '''</summary>
        Friend ReadOnly Property SQLLoginNotRecommendedCaption() As String
            Get
                Return ResourceManager.GetString("SQLLoginNotRecommendedCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Authentication is recommended. SQL Server Authentication is provided for your convenience for situations where it is may not possible to use Windows authentication. The SQL password may be stored in clear text in the app.config file. Great care should be used to assure that no unwanted access is provided to this file. The password is also exposed as clear text on the wire. Use the &apos;Encrypted Connection&apos; option to prevent exposing the password to network sniffers and other whippersnappers. If an SSL  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQLLoginNotRecommendedText() As String
            Get
                Return ResourceManager.GetString("SQLLoginNotRecommendedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;--add new file--&gt;.
        '''</summary>
        Friend ReadOnly Property SQLRunbookNewFileListBoxItem() As String
            Get
                Return ResourceManager.GetString("SQLRunbookNewFileListBoxItem", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property StartConversation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartConversation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add or Select a SQL Instance.
        '''</summary>
        Friend ReadOnly Property StartPlanning() As String
            Get
                Return ResourceManager.GetString("StartPlanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a String (text).
        '''</summary>
        Friend ReadOnly Property StringAdvOptions() As String
            Get
                Return ResourceManager.GetString("StringAdvOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to str.
        '''</summary>
        Friend ReadOnly Property StringAdvOptionsAbbr() As String
            Get
                Return ResourceManager.GetString("StringAdvOptionsAbbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text entry field that allows you to enter [{0}] value for this setting..
        '''</summary>
        Friend ReadOnly Property StringAdvOptionsHelp() As String
            Get
                Return ResourceManager.GetString("StringAdvOptionsHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ComboBox that allows you to enter values of type [{0}] for [{1}].
        '''</summary>
        Friend ReadOnly Property StringListAdvOptionsHelp() As String
            Get
                Return ResourceManager.GetString("StringListAdvOptionsHelp", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TwoHeadedDB() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoHeadedDB", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property TwoHeadedDb288() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoHeadedDb288", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only local system Administrators can configure the SQLClue Automation Controller Service..
        '''</summary>
        Friend ReadOnly Property UnauthorizedInstallUser() As String
            Get
                Return ResourceManager.GetString("UnauthorizedInstallUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Unsaved Changes.
        '''</summary>
        Friend ReadOnly Property UnsavedChangesCaption() As String
            Get
                Return ResourceManager.GetString("UnsavedChangesCaption", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
