'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.468
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RepositoryConnectionTimeout() As Integer
            Get
                Return CType(Me("RepositoryConnectionTimeout"),Integer)
            End Get
            Set
                Me("RepositoryConnectionTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositoryDatabaseName() As String
            Get
                Return CType(Me("RepositoryDatabaseName"),String)
            End Get
            Set
                Me("RepositoryDatabaseName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositoryInstanceName() As String
            Get
                Return CType(Me("RepositoryInstanceName"),String)
            End Get
            Set
                Me("RepositoryInstanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RepositoryUseTrustedConnection() As Boolean
            Get
                Return CType(Me("RepositoryUseTrustedConnection"),Boolean)
            End Get
            Set
                Me("RepositoryUseTrustedConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RepositoryEncryptConnection() As Boolean
            Get
                Return CType(Me("RepositoryEncryptConnection"),Boolean)
            End Get
            Set
                Me("RepositoryEncryptConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RepositoryTrustServerCertificate() As Boolean
            Get
                Return CType(Me("RepositoryTrustServerCertificate"),Boolean)
            End Get
            Set
                Me("RepositoryTrustServerCertificate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositorySQLLoginName() As String
            Get
                Return CType(Me("RepositorySQLLoginName"),String)
            End Get
            Set
                Me("RepositorySQLLoginName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositorySQLLoginPassword() As String
            Get
                Return CType(Me("RepositorySQLLoginPassword"),String)
            End Get
            Set
                Me("RepositorySQLLoginPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RepositoryNetworkLibrary() As String
            Get
                Return CType(Me("RepositoryNetworkLibrary"),String)
            End Get
            Set
                Me("RepositoryNetworkLibrary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property RunbookConnectionTimeout() As Integer
            Get
                Return CType(Me("RunbookConnectionTimeout"),Integer)
            End Get
            Set
                Me("RunbookConnectionTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RepositoryEnabled() As Boolean
            Get
                Return CType(Me("RepositoryEnabled"),Boolean)
            End Get
            Set
                Me("RepositoryEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunbookDatabaseName() As String
            Get
                Return CType(Me("RunbookDatabaseName"),String)
            End Get
            Set
                Me("RunbookDatabaseName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RunbookEnabled() As Boolean
            Get
                Return CType(Me("RunbookEnabled"),Boolean)
            End Get
            Set
                Me("RunbookEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RunbookEncryptConnection() As Boolean
            Get
                Return CType(Me("RunbookEncryptConnection"),Boolean)
            End Get
            Set
                Me("RunbookEncryptConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunbookInstanceName() As String
            Get
                Return CType(Me("RunbookInstanceName"),String)
            End Get
            Set
                Me("RunbookInstanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunbookNetworkLibrary() As String
            Get
                Return CType(Me("RunbookNetworkLibrary"),String)
            End Get
            Set
                Me("RunbookNetworkLibrary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunbookSQLLoginName() As String
            Get
                Return CType(Me("RunbookSQLLoginName"),String)
            End Get
            Set
                Me("RunbookSQLLoginName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RunbookSQLLoginPassword() As String
            Get
                Return CType(Me("RunbookSQLLoginPassword"),String)
            End Get
            Set
                Me("RunbookSQLLoginPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RunbookTrustServerCertificate() As Boolean
            Get
                Return CType(Me("RunbookTrustServerCertificate"),Boolean)
            End Get
            Set
                Me("RunbookTrustServerCertificate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RunbookUseTrustedConnection() As Boolean
            Get
                Return CType(Me("RunbookUseTrustedConnection"),Boolean)
            End Get
            Set
                Me("RunbookUseTrustedConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property TimerIntervalSeconds() As Integer
            Get
                Return CType(Me("TimerIntervalSeconds"),Integer)
            End Get
            Set
                Me("TimerIntervalSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MaxConcurrentArchives() As Integer
            Get
                Return CType(Me("MaxConcurrentArchives"),Integer)
            End Get
            Set
                Me("MaxConcurrentArchives") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("900")>  _
        Public Property DocumentMonitorSleepSeconds() As Integer
            Get
                Return CType(Me("DocumentMonitorSleepSeconds"),Integer)
            End Get
            Set
                Me("DocumentMonitorSleepSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WaitBetweenDocumentsSeconds() As Integer
            Get
                Return CType(Me("WaitBetweenDocumentsSeconds"),Integer)
            End Get
            Set
                Me("WaitBetweenDocumentsSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TargetHandshakeConnectionTimeout() As Integer
            Get
                Return CType(Me("TargetHandshakeConnectionTimeout"),Integer)
            End Get
            Set
                Me("TargetHandshakeConnectionTimeout") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SQLClueSvc.My.MySettings
            Get
                Return Global.SQLClueSvc.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
