'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TraceEvents
    Public Property EventCategory As String
    Public Property EventClass As String
    Public Property SubClass As String
    Public Property Database As String
    Public Property Login As String
    Public Property Application As String
    Public Property StartTime As Date
    Public Property Host As String
    Public Property ObjectType As String
    Public Property ExtendedInfo As String

End Class
