'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.468
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cCommon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ActiveDirectory.
        '''</summary>
        Friend ReadOnly Property ActiveDirectory() As String
            Get
                Return ResourceManager.GetString("ActiveDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alerts.
        '''</summary>
        Friend ReadOnly Property Alerts() As String
            Get
                Return ResourceManager.GetString("Alerts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AlertSystem.
        '''</summary>
        Friend ReadOnly Property AlertSystem() As String
            Get
                Return ResourceManager.GetString("AlertSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid column name &apos;pvt_key_last_backup_date&apos;..
        '''</summary>
        Friend ReadOnly Property AllowedCertificateScriptingException() As String
            Get
                Return ResourceManager.GetString("AllowedCertificateScriptingException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ApplicationRoles.
        '''</summary>
        Friend ReadOnly Property ApplicationRoles() As String
            Get
                Return ResourceManager.GetString("ApplicationRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property ArchiveAdd() As String
            Get
                Return ResourceManager.GetString("ArchiveAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding database [{0}] to Archive.
        '''</summary>
        Friend ReadOnly Property ArchiveAddDatabase() As String
            Get
                Return ResourceManager.GetString("ArchiveAddDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change.
        '''</summary>
        Friend ReadOnly Property ArchiveChange() As String
            Get
                Return ResourceManager.GetString("ArchiveChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected to Archive target [{0}].
        '''</summary>
        Friend ReadOnly Property ArchiveConnected() As String
            Get
                Return ResourceManager.GetString("ArchiveConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error processing DDL events from remote server [{0}]..
        '''</summary>
        Friend ReadOnly Property ArchiveDDLEventsException() As String
            Get
                Return ResourceManager.GetString("ArchiveDDLEventsException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property ArchiveDelete() As String
            Get
                Return ResourceManager.GetString("ArchiveDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in method [{0}] while archiving [{1}].[{2}]..
        '''</summary>
        Friend ReadOnly Property ArchiveException() As String
            Get
                Return ResourceManager.GetString("ArchiveException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target SQL Instance {0} did not respond to handshake. Archive will be rescheduled..
        '''</summary>
        Friend ReadOnly Property ArchiveHandShakeFailed() As String
            Get
                Return ResourceManager.GetString("ArchiveHandShakeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Writing archive log record.
        '''</summary>
        Friend ReadOnly Property ArchiveLogResult() As String
            Get
                Return ResourceManager.GetString("ArchiveLogResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select IsNull(mirroring_role_desc,&apos;none&apos;) from sys.database_mirroring where database_id = &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property ArchiveMirrorQuery() As String
            Get
                Return ResourceManager.GetString("ArchiveMirrorQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to load a &apos;{0}&apos; row for ScheduleId [{1}] for SQLInstance [{2}].
        '''</summary>
        Friend ReadOnly Property ArchiveNoRow() As String
            Get
                Return ResourceManager.GetString("ArchiveNoRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database level archive ended abnormally SQLInstance: [{0}]; db: [{1}].
        '''</summary>
        Friend ReadOnly Property ArchiveOfDatabaseFailed() As String
            Get
                Return ResourceManager.GetString("ArchiveOfDatabaseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server level archive ended abnormally SQLInstance: [{0}].
        '''</summary>
        Friend ReadOnly Property ArchiveOfServerFailed() As String
            Get
                Return ResourceManager.GetString("ArchiveOfServerFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheduling next run date.
        '''</summary>
        Friend ReadOnly Property ArchiveReschedule() As String
            Get
                Return ResourceManager.GetString("ArchiveReschedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error loading Settings [{0}]..
        '''</summary>
        Friend ReadOnly Property ArchiveSettingsLoadFailed() As String
            Get
                Return ResourceManager.GetString("ArchiveSettingsLoadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLInstance [{0}] Database [{1}] not archive because database status is [{2}].
        '''</summary>
        Friend ReadOnly Property ArchiveStatusLiteral() As String
            Get
                Return ResourceManager.GetString("ArchiveStatusLiteral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unexpected Archive e.Result [{0}].
        '''</summary>
        Friend ReadOnly Property ArchiveUnexpectedResult() As String
            Get
                Return ResourceManager.GetString("ArchiveUnexpectedResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assemblies.
        '''</summary>
        Friend ReadOnly Property Assemblies() As String
            Get
                Return ResourceManager.GetString("Assemblies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AsymmetricKeys.
        '''</summary>
        Friend ReadOnly Property AsymmetricKeys() As String
            Get
                Return ResourceManager.GetString("AsymmetricKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attributes.
        '''</summary>
        Friend ReadOnly Property Attributes() As String
            Get
                Return ResourceManager.GetString("Attributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Audits.
        '''</summary>
        Friend ReadOnly Property Audits() As String
            Get
                Return ResourceManager.GetString("Audits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackupDevices.
        '''</summary>
        Friend ReadOnly Property BackupDevices() As String
            Get
                Return ResourceManager.GetString("BackupDevices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificates.
        '''</summary>
        Friend ReadOnly Property Certificates() As String
            Get
                Return ResourceManager.GetString("Certificates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /**************** Begin {0} *****************.
        '''</summary>
        Friend ReadOnly Property CommentBegin() As String
            Get
                Return ResourceManager.GetString("CommentBegin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ****************** End {0} ******************/.
        '''</summary>
        Friend ReadOnly Property CommentEnd() As String
            Get
                Return ResourceManager.GetString("CommentEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line1Blank.
        '''</summary>
        Friend ReadOnly Property CompareLine1Blank() As String
            Get
                Return ResourceManager.GetString("CompareLine1Blank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line2Blank.
        '''</summary>
        Friend ReadOnly Property CompareLine2Blank() As String
            Get
                Return ResourceManager.GetString("CompareLine2Blank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LineDifferent.
        '''</summary>
        Friend ReadOnly Property CompareLineDifferent() As String
            Get
                Return ResourceManager.GetString("CompareLineDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LineMatch.
        '''</summary>
        Friend ReadOnly Property CompareLineMatch() As String
            Get
                Return ResourceManager.GetString("CompareLineMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name1Blank.
        '''</summary>
        Friend ReadOnly Property CompareName1Blank() As String
            Get
                Return ResourceManager.GetString("CompareName1Blank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name2Blank.
        '''</summary>
        Friend ReadOnly Property CompareName2Blank() As String
            Get
                Return ResourceManager.GetString("CompareName2Blank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NamesDifferent.
        '''</summary>
        Friend ReadOnly Property CompareNamesDifferent() As String
            Get
                Return ResourceManager.GetString("CompareNamesDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NamesMatch.
        '''</summary>
        Friend ReadOnly Property CompareNamesMatch() As String
            Get
                Return ResourceManager.GetString("CompareNamesMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration.
        '''</summary>
        Friend ReadOnly Property Configuration() As String
            Get
                Return ResourceManager.GetString("Configuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credentials.
        '''</summary>
        Friend ReadOnly Property Credentials() As String
            Get
                Return ResourceManager.GetString("Credentials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CryptographicProviders.
        '''</summary>
        Friend ReadOnly Property CryptographicProviders() As String
            Get
                Return ResourceManager.GetString("CryptographicProviders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database.
        '''</summary>
        Friend ReadOnly Property Database() As String
            Get
                Return ResourceManager.GetString("Database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DatabaseAuditSpecifications.
        '''</summary>
        Friend ReadOnly Property DatabaseAuditSpecifications() As String
            Get
                Return ResourceManager.GetString("DatabaseAuditSpecifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to event_notifications.
        '''</summary>
        Friend ReadOnly Property DatabaseEventNotifciationsCatalog() As String
            Get
                Return ResourceManager.GetString("DatabaseEventNotifciationsCatalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DatabaseMasterKey.
        '''</summary>
        Friend ReadOnly Property DatabaseMasterKey() As String
            Get
                Return ResourceManager.GetString("DatabaseMasterKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DatabaseOptions.
        '''</summary>
        Friend ReadOnly Property DatabaseOptions() As String
            Get
                Return ResourceManager.GetString("DatabaseOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Databases.
        '''</summary>
        Friend ReadOnly Property Databases() As String
            Get
                Return ResourceManager.GetString("Databases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to access database {0} on SQL Server {1} for scripting.
        '''It may be offline..
        '''</summary>
        Friend ReadOnly Property DBOffline() As String
            Get
                Return ResourceManager.GetString("DBOffline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defaults.
        '''</summary>
        Friend ReadOnly Property Defaults() As String
            Get
                Return ResourceManager.GetString("Defaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Endpoints.
        '''</summary>
        Friend ReadOnly Property Endpoints() As String
            Get
                Return ResourceManager.GetString("Endpoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EventNotifications.
        '''</summary>
        Friend ReadOnly Property EventNotifications() As String
            Get
                Return ResourceManager.GetString("EventNotifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FullTextCatalogs.
        '''</summary>
        Friend ReadOnly Property FullTextCatalogs() As String
            Get
                Return ResourceManager.GetString("FullTextCatalogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FullTextService.
        '''</summary>
        Friend ReadOnly Property FullTextService() As String
            Get
                Return ResourceManager.GetString("FullTextService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FullTextStopLists.
        '''</summary>
        Friend ReadOnly Property FullTextStopLists() As String
            Get
                Return ResourceManager.GetString("FullTextStopLists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Friend ReadOnly Property Information() As String
            Get
                Return ResourceManager.GetString("Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Item [{0}] scripting complete.
        '''</summary>
        Friend ReadOnly Property ItemScriptingCompletionMessage() As String
            Get
                Return ResourceManager.GetString("ItemScriptingCompletionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scripting item [{0}].
        '''</summary>
        Friend ReadOnly Property ItemScriptingStartMessage() As String
            Get
                Return ResourceManager.GetString("ItemScriptingStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jobs.
        '''</summary>
        Friend ReadOnly Property Jobs() As String
            Get
                Return ResourceManager.GetString("Jobs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JobServer.
        '''</summary>
        Friend ReadOnly Property JobServer() As String
            Get
                Return ResourceManager.GetString("JobServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LinkedServers.
        '''</summary>
        Friend ReadOnly Property LinkedServers() As String
            Get
                Return ResourceManager.GetString("LinkedServers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logins.
        '''</summary>
        Friend ReadOnly Property Logins() As String
            Get
                Return ResourceManager.GetString("Logins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail.
        '''</summary>
        Friend ReadOnly Property Mail() As String
            Get
                Return ResourceManager.GetString("Mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MessageTypes.
        '''</summary>
        Friend ReadOnly Property MessageTypes() As String
            Get
                Return ResourceManager.GetString("MessageTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIRROR.
        '''</summary>
        Friend ReadOnly Property MirrorRoleDescription() As String
            Get
                Return ResourceManager.GetString("MirrorRoleDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to |.
        '''</summary>
        Friend ReadOnly Property NodePathDelimiter() As String
            Get
                Return ResourceManager.GetString("NodePathDelimiter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item not supported in Express Edition SQL Server.
        '''</summary>
        Friend ReadOnly Property NoExpressSupport() As String
            Get
                Return ResourceManager.GetString("NoExpressSupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OleDbProviders.
        '''</summary>
        Friend ReadOnly Property OleDbProviders() As String
            Get
                Return ResourceManager.GetString("OleDbProviders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operators.
        '''</summary>
        Friend ReadOnly Property Operators() As String
            Get
                Return ResourceManager.GetString("Operators", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder.
        '''</summary>
        Friend ReadOnly Property OriginFile() As String
            Get
                Return ResourceManager.GetString("OriginFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repository.
        '''</summary>
        Friend ReadOnly Property OriginRepository() As String
            Get
                Return ResourceManager.GetString("OriginRepository", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQLInstance.
        '''</summary>
        Friend ReadOnly Property OriginSQLInstance() As String
            Get
                Return ResourceManager.GetString("OriginSQLInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PartitionFunctions.
        '''</summary>
        Friend ReadOnly Property PartitionFunctions() As String
            Get
                Return ResourceManager.GetString("PartitionFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PartitionSchemes.
        '''</summary>
        Friend ReadOnly Property PartitionSchemes() As String
            Get
                Return ResourceManager.GetString("PartitionSchemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PlanGuides.
        '''</summary>
        Friend ReadOnly Property PlanGuides() As String
            Get
                Return ResourceManager.GetString("PlanGuides", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policies.
        '''</summary>
        Friend ReadOnly Property Policies() As String
            Get
                Return ResourceManager.GetString("Policies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priorities.
        '''</summary>
        Friend ReadOnly Property Priorities() As String
            Get
                Return ResourceManager.GetString("Priorities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Properties.
        '''</summary>
        Friend ReadOnly Property Properties() As String
            Get
                Return ResourceManager.GetString("Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ProxyAccount.
        '''</summary>
        Friend ReadOnly Property ProxyAccount() As String
            Get
                Return ResourceManager.GetString("ProxyAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ProxyAccounts.
        '''</summary>
        Friend ReadOnly Property ProxyAccounts() As String
            Get
                Return ResourceManager.GetString("ProxyAccounts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queues.
        '''</summary>
        Friend ReadOnly Property Queues() As String
            Get
                Return ResourceManager.GetString("Queues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RemoteServiceBindings.
        '''</summary>
        Friend ReadOnly Property RemoteServiceBindings() As String
            Get
                Return ResourceManager.GetString("RemoteServiceBindings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ResourceGovernor.
        '''</summary>
        Friend ReadOnly Property ResourceGovernor() As String
            Get
                Return ResourceManager.GetString("ResourceGovernor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roles.
        '''</summary>
        Friend ReadOnly Property Roles() As String
            Get
                Return ResourceManager.GetString("Roles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Routes.
        '''</summary>
        Friend ReadOnly Property Routes() As String
            Get
                Return ResourceManager.GetString("Routes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rules.
        '''</summary>
        Friend ReadOnly Property Rules() As String
            Get
                Return ResourceManager.GetString("Rules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INFORMATION_SCHEMA.
        '''</summary>
        Friend ReadOnly Property SchemaINFORMATION_SCHEMA() As String
            Get
                Return ResourceManager.GetString("SchemaINFORMATION_SCHEMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schemas.
        '''</summary>
        Friend ReadOnly Property Schemas() As String
            Get
                Return ResourceManager.GetString("Schemas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sys.
        '''</summary>
        Friend ReadOnly Property SchemaSys() As String
            Get
                Return ResourceManager.GetString("SchemaSys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server.
        '''</summary>
        Friend ReadOnly Property Server() As String
            Get
                Return ResourceManager.GetString("Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServerAuditSpecifications.
        '''</summary>
        Friend ReadOnly Property ServerAuditSpecifications() As String
            Get
                Return ResourceManager.GetString("ServerAuditSpecifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to server_event_notifications.
        '''</summary>
        Friend ReadOnly Property ServerEventNotificationsCatalog() As String
            Get
                Return ResourceManager.GetString("ServerEventNotificationsCatalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServiceBroker.
        '''</summary>
        Friend ReadOnly Property ServiceBroker() As String
            Get
                Return ResourceManager.GetString("ServiceBroker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServiceContracts.
        '''</summary>
        Friend ReadOnly Property ServiceContracts() As String
            Get
                Return ResourceManager.GetString("ServiceContracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServiceMasterKey.
        '''</summary>
        Friend ReadOnly Property ServiceMasterKey() As String
            Get
                Return ResourceManager.GetString("ServiceMasterKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Services.
        '''</summary>
        Friend ReadOnly Property Services() As String
            Get
                Return ResourceManager.GetString("Services", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT n.[name] AS [Name]  
        ''', CASE n.[parent_class_desc]  
        '''   WHEN &apos;DATABASE&apos; THEN &apos;DATABASE&apos;  
        '''   WHEN &apos;SERVER&apos; THEN &apos;SERVER&apos;  
        '''   ELSE &apos;QUEUE &apos; + OBJECT_NAME(n.[parent_id]) END AS [Scope]  
        ''', CASE WHEN n.[creator_sid] IS NOT NULL 
        '''       THEN &apos;True&apos; 
        '''       ELSE &apos;False&apos; END AS [FAN_IN]  
        ''', n.[service_name] COLLATE DATABASE_DEFAULT AS [Service]  
        ''', CAST(n.[broker_instance] AS NVARCHAR(50)) AS [ServiceBrokerInstance]  
        ''', ISNULL(d.[name],&apos;not local database&apos;) AS [DatabaseName]  
        ''', SUSER_NAME(n.pri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sEventNotificationsQueryTemplate() As String
            Get
                Return ResourceManager.GetString("sEventNotificationsQueryTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMO is in a bad state. This may be caused by an SMO
        '''issue related to Transparent Data Encryption (TDE)
        '''if TDE is enabled on the database. The problem has
        '''been reported and confirmed at connect.microsoft.com
        '''and is to be fixed in a future SQL Server release.
        '''Workaround: Restart SQLClue. Try using an archived
        '''script for the database compare or compare all
        '''databases on the SQL Server 2008 instance instead
        '''of comparing only one database..
        '''</summary>
        Friend ReadOnly Property SMOBadState() As String
            Get
                Return ResourceManager.GetString("SMOBadState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend ReadOnly Property SMOID() As String
            Get
                Return ResourceManager.GetString("SMOID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsAccessible.
        '''</summary>
        Friend ReadOnly Property SMOIsAccessible() As String
            Get
                Return ResourceManager.GetString("SMOIsAccessible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsFixedRole.
        '''</summary>
        Friend ReadOnly Property SMOIsFixedRole() As String
            Get
                Return ResourceManager.GetString("SMOIsFixedRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsSystemObject.
        '''</summary>
        Friend ReadOnly Property SMOIsSystemObject() As String
            Get
                Return ResourceManager.GetString("SMOIsSystemObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend ReadOnly Property SMOLanguage() As String
            Get
                Return ResourceManager.GetString("SMOLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property SMOName() As String
            Get
                Return ResourceManager.GetString("SMOName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schema.
        '''</summary>
        Friend ReadOnly Property SMOSchema() As String
            Get
                Return ResourceManager.GetString("SMOSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeAdd() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeChange() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property SQLCfgArchiveTypeDelete() As String
            Get
                Return ResourceManager.GetString("SQLCfgArchiveTypeDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StartupProcedures.
        '''</summary>
        Friend ReadOnly Property StartupProcedures() As String
            Get
                Return ResourceManager.GetString("StartupProcedures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StoredProcedures.
        '''</summary>
        Friend ReadOnly Property StoredProcedures() As String
            Get
                Return ResourceManager.GetString("StoredProcedures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SymmetricKeys.
        '''</summary>
        Friend ReadOnly Property SymmetricKeys() As String
            Get
                Return ResourceManager.GetString("SymmetricKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Synonyms.
        '''</summary>
        Friend ReadOnly Property Synonyms() As String
            Get
                Return ResourceManager.GetString("Synonyms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tables.
        '''</summary>
        Friend ReadOnly Property Tables() As String
            Get
                Return ResourceManager.GetString("Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TargetServers.
        '''</summary>
        Friend ReadOnly Property TargetServers() As String
            Get
                Return ResourceManager.GetString("TargetServers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Triggers.
        '''</summary>
        Friend ReadOnly Property Triggers() As String
            Get
                Return ResourceManager.GetString("Triggers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedAggregates.
        '''</summary>
        Friend ReadOnly Property UserDefinedAggregates() As String
            Get
                Return ResourceManager.GetString("UserDefinedAggregates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedDataTypes.
        '''</summary>
        Friend ReadOnly Property UserDefinedDataTypes() As String
            Get
                Return ResourceManager.GetString("UserDefinedDataTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedFunctions.
        '''</summary>
        Friend ReadOnly Property UserDefinedFunctions() As String
            Get
                Return ResourceManager.GetString("UserDefinedFunctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedMessages.
        '''</summary>
        Friend ReadOnly Property UserDefinedMessages() As String
            Get
                Return ResourceManager.GetString("UserDefinedMessages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedTableTypes.
        '''</summary>
        Friend ReadOnly Property UserDefinedTableTypes() As String
            Get
                Return ResourceManager.GetString("UserDefinedTableTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserDefinedTypes.
        '''</summary>
        Friend ReadOnly Property UserDefinedTypes() As String
            Get
                Return ResourceManager.GetString("UserDefinedTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users.
        '''</summary>
        Friend ReadOnly Property Users() As String
            Get
                Return ResourceManager.GetString("Users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Views.
        '''</summary>
        Friend ReadOnly Property Views() As String
            Get
                Return ResourceManager.GetString("Views", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XMLSchemaCollections.
        '''</summary>
        Friend ReadOnly Property XMLSchemaCollections() As String
            Get
                Return ResourceManager.GetString("XMLSchemaCollections", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
